version: '3'

services:
    caddy:
      image: caddy:latest
      restart: unless-stopped
      cap_add:
        - NET_ADMIN
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
      volumes:
        - ${BASE_PATH}/conf:/etc/caddy
        - ${BASE_PATH}/site:/srv
        - caddy_data:/data
        - caddy_config:/config
      environment:
        - DOMAIN=${APP_BASE_URL}

    db:
        image: postgres:16
        volumes:
            - ${BASE_PATH}/database:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}
    app:
        image: joplin/server:latest
        volumes:
          - ${BASE_PATH}/files:/mnt/files
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=db
            - STORAGE_DRIVER=Type=Filesystem; Path=/mnt/files
volumes:
  caddy_data:
  caddy_config:
